// <auto-generated />
using System;
using FlightBooking.Service.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FlightBooking.Service.Migrations
{
    [DbContext(typeof(FlightBookingContext))]
    partial class FlightBookingContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("FlightBooking.Service.Data.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("BookingNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("BookingOrderId")
                        .HasColumnType("int");

                    b.Property<int>("BookingStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("FlightFareId")
                        .HasColumnType("int");

                    b.Property<int>("FlightId")
                        .HasColumnType("int");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("BookingOrderId");

                    b.HasIndex("FlightFareId");

                    b.HasIndex("FlightId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("FlightBooking.Service.Data.Models.BookingOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("NumberOfAdults")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfChildren")
                        .HasColumnType("int");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("OrderStatus")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("BookingOrders");
                });

            modelBuilder.Entity("FlightBooking.Service.Data.Models.FlightFare", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FareCode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FareName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("FlightInformationId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("SeatCapacity")
                        .HasColumnType("int");

                    b.Property<int>("SeatReserved")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("FlightInformationId");

                    b.ToTable("FlightFares");
                });

            modelBuilder.Entity("FlightBooking.Service.Data.Models.FlightInformation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Airline")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ArrivalDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DepartureDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FlightNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("SeatCapacity")
                        .HasColumnType("int");

                    b.Property<int>("SeatReserved")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("FlightInformation");
                });

            modelBuilder.Entity("FlightBooking.Service.Data.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookingOrderId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MetaData")
                        .HasColumnType("longtext");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PaymentChannel")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PaymentReference")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("TransactionAmount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("BookingOrderId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("FlightBooking.Service.Data.Models.ReservedSeat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BookingId")
                        .HasColumnType("int");

                    b.Property<string>("BookingNumber")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("FlightInformationId")
                        .HasColumnType("int");

                    b.Property<string>("FlightNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsReserved")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SeatNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("BookingId")
                        .IsUnique();

                    b.HasIndex("FlightInformationId");

                    b.ToTable("ReservedSeats");
                });

            modelBuilder.Entity("FlightBooking.Service.Data.Models.Booking", b =>
                {
                    b.HasOne("FlightBooking.Service.Data.Models.BookingOrder", "BookingOrder")
                        .WithMany("Bookings")
                        .HasForeignKey("BookingOrderId")
                        .IsRequired();

                    b.HasOne("FlightBooking.Service.Data.Models.FlightFare", "FlightFare")
                        .WithMany("Bookings")
                        .HasForeignKey("FlightFareId")
                        .IsRequired();

                    b.HasOne("FlightBooking.Service.Data.Models.FlightInformation", "FlightInformation")
                        .WithMany("Bookings")
                        .HasForeignKey("FlightId")
                        .IsRequired();

                    b.Navigation("BookingOrder");

                    b.Navigation("FlightFare");

                    b.Navigation("FlightInformation");
                });

            modelBuilder.Entity("FlightBooking.Service.Data.Models.FlightFare", b =>
                {
                    b.HasOne("FlightBooking.Service.Data.Models.FlightInformation", "FlightInformation")
                        .WithMany("FlightFares")
                        .HasForeignKey("FlightInformationId")
                        .IsRequired();

                    b.Navigation("FlightInformation");
                });

            modelBuilder.Entity("FlightBooking.Service.Data.Models.Payment", b =>
                {
                    b.HasOne("FlightBooking.Service.Data.Models.BookingOrder", "BookingOrder")
                        .WithMany("Payments")
                        .HasForeignKey("BookingOrderId")
                        .IsRequired();

                    b.Navigation("BookingOrder");
                });

            modelBuilder.Entity("FlightBooking.Service.Data.Models.ReservedSeat", b =>
                {
                    b.HasOne("FlightBooking.Service.Data.Models.Booking", "Booking")
                        .WithOne("ReservedSeat")
                        .HasForeignKey("FlightBooking.Service.Data.Models.ReservedSeat", "BookingId");

                    b.HasOne("FlightBooking.Service.Data.Models.FlightInformation", "FlightInformation")
                        .WithMany("ReservedSeats")
                        .HasForeignKey("FlightInformationId")
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("FlightInformation");
                });

            modelBuilder.Entity("FlightBooking.Service.Data.Models.Booking", b =>
                {
                    b.Navigation("ReservedSeat");
                });

            modelBuilder.Entity("FlightBooking.Service.Data.Models.BookingOrder", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("FlightBooking.Service.Data.Models.FlightFare", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("FlightBooking.Service.Data.Models.FlightInformation", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("FlightFares");

                    b.Navigation("ReservedSeats");
                });
#pragma warning restore 612, 618
        }
    }
}
